PROJECT_NAME = "<%= _.slugify(name) %>"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = PROJECT_NAME + ".local"
  config.vm.provision :ansible do |a|
  	a.groups = {
      "dockerhost" => ["default"],
  		"vagrant" => ["default"]
  	}
  	a.playbook = "ansible/vagrant.yml"
    a.host_key_checking = false
  end
  config.vm.synced_folder ".", "/opt/" + PROJECT_NAME
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  config.vm.network "private_network", type: :dhcp
end
